/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InvestmentFundsRouteImport } from './routes/investment-funds'
import { Route as InvestWithUsRouteImport } from './routes/invest-with-us'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as AbouteRouteImport } from './routes/aboute'
import { Route as IndexRouteImport } from './routes/index'

const InvestmentFundsRoute = InvestmentFundsRouteImport.update({
  id: '/investment-funds',
  path: '/investment-funds',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestWithUsRoute = InvestWithUsRouteImport.update({
  id: '/invest-with-us',
  path: '/invest-with-us',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const AbouteRoute = AbouteRouteImport.update({
  id: '/aboute',
  path: '/aboute',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aboute': typeof AbouteRoute
  '/company': typeof CompanyRoute
  '/contact-us': typeof ContactUsRoute
  '/invest-with-us': typeof InvestWithUsRoute
  '/investment-funds': typeof InvestmentFundsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aboute': typeof AbouteRoute
  '/company': typeof CompanyRoute
  '/contact-us': typeof ContactUsRoute
  '/invest-with-us': typeof InvestWithUsRoute
  '/investment-funds': typeof InvestmentFundsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aboute': typeof AbouteRoute
  '/company': typeof CompanyRoute
  '/contact-us': typeof ContactUsRoute
  '/invest-with-us': typeof InvestWithUsRoute
  '/investment-funds': typeof InvestmentFundsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aboute'
    | '/company'
    | '/contact-us'
    | '/invest-with-us'
    | '/investment-funds'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aboute'
    | '/company'
    | '/contact-us'
    | '/invest-with-us'
    | '/investment-funds'
  id:
    | '__root__'
    | '/'
    | '/aboute'
    | '/company'
    | '/contact-us'
    | '/invest-with-us'
    | '/investment-funds'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbouteRoute: typeof AbouteRoute
  CompanyRoute: typeof CompanyRoute
  ContactUsRoute: typeof ContactUsRoute
  InvestWithUsRoute: typeof InvestWithUsRoute
  InvestmentFundsRoute: typeof InvestmentFundsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/investment-funds': {
      id: '/investment-funds'
      path: '/investment-funds'
      fullPath: '/investment-funds'
      preLoaderRoute: typeof InvestmentFundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invest-with-us': {
      id: '/invest-with-us'
      path: '/invest-with-us'
      fullPath: '/invest-with-us'
      preLoaderRoute: typeof InvestWithUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aboute': {
      id: '/aboute'
      path: '/aboute'
      fullPath: '/aboute'
      preLoaderRoute: typeof AbouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbouteRoute: AbouteRoute,
  CompanyRoute: CompanyRoute,
  ContactUsRoute: ContactUsRoute,
  InvestWithUsRoute: InvestWithUsRoute,
  InvestmentFundsRoute: InvestmentFundsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
